"use client";
import { useCallback, useEffect, useState } from "react";

type D = Record<string, any>;
type Staff = { username: string; display_name: string; role: "ADMIN" | "DOCTOR" | "PHARMACY" };
const roles = [
  { id: "admin", name: "Billing desk", person: "Riya Menon", task: "Rooms, invoices and payers", icon: "₹" },
  { id: "doctor", name: "Doctor", person: "Dr Mira Sen", task: "Care notes and orders", icon: "DR" },
  { id: "pharmacy", name: "Pharmacy", person: "Nisha Shah", task: "Prescriptions and stock", icon: "Rx" },
];
const money = (n?: number) => `₹${((n || 0) / 100).toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const day = (offset = 0) => new Date(Date.now() + offset * 86400000).toISOString().slice(0, 10);
const when = (s: string) => new Date(s).toLocaleDateString("en-IN", { day: "numeric", month: "short" });
async function api(path: string, init: RequestInit = {}) {
  const token = typeof window === "undefined" ? "" : sessionStorage.getItem("tiveri_token") || "";
  const res = await fetch(`/api${path}`, { cache: "no-store", ...init, headers: { ...(init.body ? { "Content-Type": "application/json" } : {}), ...(token ? { Authorization: `Bearer ${token}` } : {}), ...init.headers } });
  const body = await res.json().catch(() => ({}));
  if (!res.ok) { if (res.status === 401 && path !== "/auth/login") sessionStorage.removeItem("tiveri_token"); throw new Error(body.detail || `Request failed (${res.status})`); }
  return body;
}
const post = (path: string, body: D) => api(path, { method: "POST", body: JSON.stringify(body) });
function Tag({ children, tone = "blue" }: { children: React.ReactNode; tone?: string }) { return <span className={`p-tag ${tone}`}>{children}</span>; }
function Card({ title, sub, icon, children, wide = false }: { title: string; sub: string; icon: string; children: React.ReactNode; wide?: boolean }) {
  return <section className={`p-card ${wide ? "p-wide" : ""}`}><div className="p-card-head"><span className="p-card-icon">{icon}</span><div><h3>{title}</h3><small>{sub}</small></div></div>{children}</section>;
}

export default function Home() {
  const [user, setUser] = useState<Staff | null>(null);
  const [loginRole, setLoginRole] = useState("admin");
  const [password, setPassword] = useState("Demo@1234");
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [selected, setSelected] = useState("E-OPD-01");
  const [dash, setDash] = useState<D>({ worklist: [] });
  const [detail, setDetail] = useState<D>({});
  const [stock, setStock] = useState<D>({ items: [] });
  const [queue, setQueue] = useState<D>({ prescriptions: [] });
  const [note, setNote] = useState("Symptoms reviewed. Patient is stable. Follow-up and investigations explained.");
  const [provisionalIcd, setProvisionalIcd] = useState("R50.9");
  const [procedureCode, setProcedureCode] = useState("CBC");
  const [service, setService] = useState("XRAY");
  const [medicine, setMedicine] = useState("MED-A");
  const [orderQty, setOrderQty] = useState(2);
  const [instruction, setInstruction] = useState("Take as directed after food");
  const [invoiceOpen, setInvoiceOpen] = useState(false);
  const [taxReport, setTaxReport] = useState<D | null>(null);
  const [paymentMethod, setPaymentMethod] = useState("UPI");
  const [rxRef, setRxRef] = useState("RX-DEMO-01");
  const [dispenseQty, setDispenseQty] = useState(1);
  const [roomCode, setRoomCode] = useState("PRIVATE_ROOM");
  const [roomStart, setRoomStart] = useState(day());
  const [roomEnd, setRoomEnd] = useState(day(1));
  const refresh = useCallback(async (id: string) => {
    const [d, patient, s, q] = await Promise.all([api("/dashboard"), api(`/encounters/${id}`), api("/pharmacy/stock"), api("/clinical/queue")]);
    setDash(d); setDetail(patient); setStock(s); setQueue(q);
    const next = q.prescriptions?.find((r: D) => r.encounter_id === id && r.quantity > r.dispensed_quantity);
    setRxRef(previous => q.prescriptions?.some((r: D) => r.prescription_ref === previous && r.quantity > r.dispensed_quantity)
      ? previous : next?.prescription_ref || "");
  }, []);
  useEffect(() => {
    if (!sessionStorage.getItem("tiveri_token")) { setLoading(false); return; }
    api("/auth/me").then((u: Staff) => { setUser(u); setSelected("E-OPD-01"); return refresh("E-OPD-01"); })
      .catch(() => { sessionStorage.removeItem("tiveri_token"); setUser(null); }).finally(() => setLoading(false));
  }, [refresh]);
  useEffect(() => {
    if (invoiceOpen) requestAnimationFrame(() => document.getElementById("generated-invoice")?.scrollIntoView({ behavior: "smooth", block: "start" }));
  }, [invoiceOpen]);
  async function login() {
    setBusy(true); setError(""); setNotice("");
    try { const result = await post("/auth/login", { username: loginRole, password }); sessionStorage.setItem("tiveri_token", result.token); setUser(result.user); setSelected("E-OPD-01"); await refresh("E-OPD-01"); }
    catch (e) { setError((e as Error).message); } finally { setBusy(false); }
  }
  async function logout() { await api("/auth/logout", { method: "POST" }).catch(() => {}); sessionStorage.removeItem("tiveri_token"); setUser(null); setInvoiceOpen(false); setError(""); setNotice(""); }
  async function act(label: string, path: string, payload: D) { setBusy(true); setError(""); setNotice(""); try { await post(path, payload); await refresh(selected); setNotice(label); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function choose(id: string) { setSelected(id); setInvoiceOpen(false); setError(""); setNotice(""); try { await refresh(id); } catch (e) { setError((e as Error).message); } }
  async function generateInvoice() { setBusy(true); setError(""); setNotice(""); try { await post("/invoices", { encounter_id: selected }); await refresh(selected); setInvoiceOpen(true); setNotice("Invoice generated below."); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function resetDemo() { setBusy(true); setError(""); try { await post("/demo/reset", {}); sessionStorage.removeItem("tiveri_token"); setUser(null); setInvoiceOpen(false); setTaxReport(null); setNotice("Demo cases restored. Sign in to begin again."); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function loadTaxReport() { setBusy(true); setError(""); try { setTaxReport(await api(`/gstr1?month=${new Date().toISOString().slice(0, 7)}`)); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }

  if (loading) return <div className="p-loading">Opening Tiveri demo…</div>;
  if (!user) return <main className="p-login"><section className="p-login-story"><div className="p-logo"><span>✚</span><b>Tiveri</b><small>HOSPITAL OPERATIONS</small></div><div className="p-login-copy"><div className="p-kicker">DH 308 · LIVE PROJECT</div><h1>From patient care<br />to a clear bill.</h1><p>Walk through a connected hospital billing day using three staff desks and invented patient records.</p></div><div className="p-steps"><span>01 Doctor note</span><i /><span>02 Dispense</span><i /><span>03 Invoice</span></div><div className="p-login-foot">Synthetic classroom data · External portals are simulated</div></section><section className="p-login-panel"><div className="p-login-inner"><div className="p-kicker">CHOOSE A WORKSPACE</div><h2>Sign in for the demo</h2><p>Each role opens the same patient record with the actions relevant to that team.</p><div className="p-role-grid">{roles.map(r => <button key={r.id} className={`p-role ${loginRole === r.id ? "selected" : ""}`} onClick={() => setLoginRole(r.id)}><span className="p-role-icon">{r.icon}</span><span><b>{r.name}</b><small>{r.task}</small></span><span>{loginRole === r.id ? "✓" : ""}</span></button>)}</div><label className="p-field">Demo password<input type="password" value={password} onChange={e => setPassword(e.target.value)} onKeyDown={e => { if (e.key === "Enter") login(); }} /></label><div className="p-hint">Use <code>Demo@1234</code> for every role.</div>{error && <div className="p-alert error">{error}</div>}<button className="p-primary p-signin" disabled={busy} onClick={login}>{busy ? "Signing in…" : `Continue as ${roles.find(r => r.id === loginRole)?.name}`} <span>↗</span></button></div></section></main>;

  const patient = detail.patient || {}, enc = detail.encounter || {};
  const notes: D[] = detail.clinical_notes || [], items: D[] = stock.items || [];
  const activeRx = (queue.prescriptions || []).find((r: D) => r.prescription_ref === rxRef);
  const activeItem = items.find(i => i.item_code === activeRx?.item_code);
  const coverage = detail.coverage || {};
  const preauths: D[] = detail.preauths || [];
  const preauth = preauths[preauths.length - 1];
  const claim = detail.claim;
  const needsCoverage = enc.payer_route === "PMJAY" && coverage.eligibility_status !== "VERIFIED_DEMO";
  const needsPreauth = coverage.preauth_required && !preauths.some(p => p.status === "APPROVED_DEMO");
  const title = { DOCTOR: "Doctor desk", PHARMACY: "Pharmacy desk", ADMIN: "Billing desk" }[user.role];
  return <div className="p-shell"><aside className="p-sidebar"><div className="p-logo dark"><span>✚</span><b>Tiveri</b><small>HOSPITAL OPERATIONS</small></div><div className="p-side-label">WORKSPACE</div><div className="p-side-person"><span>{roles.find(r => r.id === user.username)?.icon}</span><div><b>{title}</b><small>{user.display_name}</small></div></div><div className="p-side-label">PATIENTS</div><div className="p-side-list">{(dash.worklist || []).filter((w: D) => ["E-OPD-01", "E-IPD-08", "E-IPD-02", "E-IPD-03", "E-OPD-05"].includes(w.encounter_id)).map((w: D) => <button key={w.encounter_id} className={selected === w.encounter_id ? "active" : ""} onClick={() => choose(w.encounter_id)}><span className="p-avatar">{w.patient_label?.split(" ").map((v: string) => v[0]).join("")}</span><span><b>{w.patient_label}</b><small>{w.encounter_id} · {w.setting}</small></span></button>)}</div><div className="p-sidebar-foot"><span className="p-dot" /> PostgreSQL demo connected <button onClick={logout}>Sign out ↗</button></div></aside><main className="p-main"><header className="p-topbar"><div><div className="p-kicker">DH 308 · HOSPITAL BILLING WITH HIS</div><h1>{title}</h1></div><div className="p-topright"><Tag tone="green">● Local demo</Tag><span>{user.display_name}<small>{user.role.toLowerCase()}</small></span>{user.role === "ADMIN" && <button onClick={resetDemo} disabled={busy}>Reset demo</button>}<button onClick={logout}>Sign out</button></div></header><div className="p-content">{error && <div className="p-alert error">{error}<button onClick={() => setError("")}>×</button></div>}{notice && <div className="p-alert success">✓ {notice}<button onClick={() => setNotice("")}>×</button></div>}
    <section className="p-patient"><div className="p-patient-top"><div><div className="p-kicker">PATIENT RECORD · {selected}</div><h2>{patient.display_label || "Loading patient"}</h2><p>{patient.age_years} years · {patient.sex} · {patient.city} · {patient.contact_masked}</p></div><div className="p-patient-tags"><Tag>{enc.setting}</Tag><Tag tone={enc.payer_route === "SELF" ? "green" : "purple"}>{enc.payer_route}</Tag><Tag tone={enc.status === "OPEN" ? "amber" : "green"}>{enc.status}</Tag></div></div><div className="p-patient-facts"><div><small>Patient ID</small><b>{patient.patient_id}</b></div><div><small>Blood group</small><b>{patient.blood_group || "Not recorded"}</b></div><div><small>Allergies</small><b>{patient.allergies || "Not recorded"}</b></div><div><small>Coverage</small><b>{enc.payer_label || "Self pay"}</b></div></div></section>
    <div className="p-intro"><div><div className="p-kicker">CONNECTED RECORD</div><h2>{user.role === "DOCTOR" ? "Care and orders" : user.role === "PHARMACY" ? "Dispense against an order" : "Prepare the patient bill"}</h2></div><p>{user.role === "DOCTOR" ? "Add a note, mark a delivered service, or prescribe from stocked medicines." : user.role === "PHARMACY" ? "The medicine master supplies the GST rate and the batch supplies the stock." : "Review the charges and generate an itemised invoice on this page."}</p></div>
    <div className="p-grid"><Card title="Patient history" sub="Invented clinical context" icon="⌁"><p className="p-history">{patient.history_summary || "No previous history entered for this synthetic patient."}</p><div className="p-mini-heading">Recent doctor notes</div>{notes.length ? notes.slice(0, 3).map(n => <div className="p-note" key={n.note_id}><b>{when(n.created_at)} · {n.author_username}</b><p>{n.note_text}</p>{(n.provisional_icd_code || n.procedure_code) && <small>ICD-10 {n.provisional_icd_code || "—"} · Procedure {n.procedure_code || "—"}</small>}</div>) : <p className="p-muted">No note yet.</p>}</Card>
    {user.role === "DOCTOR" && <Card title="Doctor actions" sub="Updates appear in the shared record" icon="✚"><label className="p-field">Progress note<textarea rows={3} value={note} onChange={e => setNote(e.target.value)} /></label><div className="p-two-fields"><label className="p-field">Provisional ICD-10<input value={provisionalIcd} onChange={e => setProvisionalIcd(e.target.value)} /></label><label className="p-field">Hospital service code<input value={procedureCode} onChange={e => setProcedureCode(e.target.value)} /></label></div><p className="p-fineprint">The doctor records ICD-10 and the hospital service code. Use the hospital service master for procedure charges.</p><button className="p-primary" disabled={busy || enc.status !== "OPEN"} onClick={() => act("Clinical note saved", "/clinical/notes", { encounter_id: selected, note_text: note, provisional_icd_code: provisionalIcd, procedure_code: procedureCode })}>Save clinical note</button><div className="p-divider" /><label className="p-field">Delivered service<select value={service} onChange={e => setService(e.target.value)}><option value="XRAY">X-ray investigation · ₹900</option><option value="CBC">Complete blood count · ₹350</option><option value="CONSULT">OPD consultation · ₹500</option><option value="PROC">Procedure example · ₹8,500</option></select></label><button className="p-secondary" disabled={busy || enc.status !== "OPEN"} onClick={() => act("HIS service captured once for billing", "/his/events", { encounter_id: selected, service_code: service, quantity: 1, source_event_id: `HIS-${crypto.randomUUID()}` })}>Mark service delivered</button><div className="p-divider" /><div className="p-two-fields"><label className="p-field">Medicine<select value={medicine} onChange={e => setMedicine(e.target.value)}>{items.filter(i => i.requires_prescription).map(i => <option key={i.item_code} value={i.item_code}>{i.description} · {i.tax_category === "NIL" ? "Nil" : `${i.tax_rate_bps / 100}% GST`}</option>)}</select></label><label className="p-field">Quantity<input type="number" min="1" value={orderQty} onChange={e => setOrderQty(Number(e.target.value))} /></label></div><label className="p-field">Instruction<input value={instruction} onChange={e => setInstruction(e.target.value)} /></label><button className="p-secondary" disabled={busy || enc.status !== "OPEN"} onClick={() => act("Prescription sent to pharmacy", "/clinical/prescriptions", { encounter_id: selected, item_code: medicine, quantity: orderQty, instruction })}>Create prescription</button></Card>}
    {user.role === "PHARMACY" && <Card title="Prescription queue" sub="Choose an order, then dispense" icon="Rx"><div className="p-rx-list">{(queue.prescriptions || []).filter((r: D) => r.quantity > r.dispensed_quantity).map((r: D) => <button key={r.prescription_ref} className={rxRef === r.prescription_ref ? "active" : ""} onClick={() => { setRxRef(r.prescription_ref); choose(r.encounter_id); }}><span><b>{r.patient_label}</b><small>{r.prescription_ref} · {r.item_code}</small></span><Tag tone="amber">{r.quantity - r.dispensed_quantity} left</Tag></button>)}</div>{activeRx && <div className="p-rx-detail"><b>{activeItem?.description}</b><span>{activeItem?.tax_category === "NIL" ? "Nil GST" : `${(activeItem?.tax_rate_bps || 0) / 100}% GST`} · HSN {activeItem?.hsn_code} · {activeItem?.available_units} in stock</span><small>{activeRx.instruction}</small><small>{enc.setting === "IPD" ? "IPD treatment supply: exempt in this demo" : "Separate OPD pharmacy sale: item GST applies"}</small></div>}<label className="p-field">Quantity to dispense<input type="number" min="1" value={dispenseQty} onChange={e => setDispenseQty(Number(e.target.value))} /></label><button className="p-primary" disabled={busy || !activeRx || dispenseQty < 1 || dispenseQty > activeRx.quantity - activeRx.dispensed_quantity} onClick={() => act("Medicine dispensed, stock and bill updated", "/pharmacy/dispense", { encounter_id: activeRx.encounter_id, item_code: activeRx.item_code, quantity: dispenseQty, prescription_ref: activeRx.prescription_ref, source_event_id: `DISP-${crypto.randomUUID()}` })}>Dispense from batch</button></Card>}
    {user.role === "ADMIN" && <Card title={enc.setting === "IPD" ? "Room stay" : "Billing review"} sub={enc.setting === "IPD" ? "Add the bed charge before discharge" : "Charges arrive from doctor and pharmacy"} icon="₹">{enc.setting === "IPD" ? <><div className="p-room-options"><button className={roomCode === "WARD" ? "selected" : ""} onClick={() => setRoomCode("WARD")}><span>General ward</span><b>₹2,300 / day</b><small>Exempt example</small></button><button className={roomCode === "PRIVATE_ROOM" ? "selected" : ""} onClick={() => setRoomCode("PRIVATE_ROOM")}><span>Private room</span><b>₹6,000 / day</b><small>5% GST on room charge</small></button></div><div className="p-two-fields"><label className="p-field">From<input type="date" value={roomStart} onChange={e => setRoomStart(e.target.value)} /></label><label className="p-field">To, exclusive<input type="date" value={roomEnd} onChange={e => setRoomEnd(e.target.value)} /></label></div><button className="p-secondary" disabled={busy || enc.status !== "OPEN"} onClick={() => act("Room stay added to running bill", `/encounters/${selected}/room-stays`, { room_code: roomCode, start_date: roomStart, end_date: roomEnd })}>Add room stay</button><p className="p-fineprint">A ₹6,000 non-ICU room adds ₹300 GST for one day, subject to the specified no-ITC condition.</p></> : <p className="p-history">The doctor records delivered services. Pharmacy adds only dispensed items. Review the running bill below, then generate the itemised invoice on this page.</p>}</Card>}
    </div>
    {user.role === "ADMIN" && enc.payer_route !== "SELF" && <Card title="Payer pathway" sub={`${enc.payer_label} · local simulation`} icon="₹" wide><div className="p-payer-status"><span>Coverage</span><b>{coverage.eligibility_status}</b><span>Preauthorisation</span><b>{preauth?.status || "Not requested"}</b><span>Claim</span><b>{claim?.status || "Not submitted"}</b></div><div className="p-payer-actions">{needsCoverage && <button className="p-secondary" disabled={busy} onClick={() => act("Demo beneficiary check recorded", `/coverage/${selected}/verify`, { member_ref: `SYN-${selected}` })}>Verify PM-JAY eligibility</button>}{coverage.preauth_required && !preauth && <button className="p-secondary" disabled={busy || needsCoverage} onClick={() => act("Demo preauthorisation requested", "/preauth", { encounter_id: selected, requested_paise: Math.max(detail.running_total_paise || 0, 1500000) })}>Request preauthorisation</button>}{preauth?.status === "SUBMITTED_DEMO" && <button className="p-secondary" disabled={busy} onClick={() => act("Demo preauthorisation approved", `/preauth/${preauth.preauth_id}/decision`, { approved_paise: preauth.requested_paise, reference_no: `SYN-PRE-${selected}` })}>Record preauthorisation approval</button>}{detail.invoice && !claim && <button className="p-secondary" disabled={busy} onClick={() => act("Demo claim prepared", "/claims", { invoice_id: detail.invoice.invoice_id, discharge_summary: "Synthetic discharge summary for classroom demonstration.", documents: { itemised_bill: true, discharge_summary: true } })}>Prepare claim</button>}{claim?.status === "SUBMITTED_DEMO" && <button className="p-secondary" disabled={busy} onClick={() => act("Demo payer decision recorded", `/claims/${claim.claim_id}/decision`, { approved_paise: claim.submitted_paise, reference_no: `SYN-CLM-${selected}` })}>Record claim approval</button>}{claim?.status === "APPROVED_DEMO" && detail.remaining_paise > 0 && <button className="p-secondary" disabled={busy} onClick={() => act("Payer receipt recorded", "/receipts", { invoice_id: detail.invoice.invoice_id, payer_kind: enc.payer_route === "PMJAY" ? "SCHEME" : enc.payer_route === "CORPORATE" ? "CORPORATE" : "INSURER", amount_paise: Math.min(claim.approved_paise, detail.remaining_paise), method: "TRANSFER" })}>Record payer payment</button>}</div><p className="p-fineprint">Insurer, CGHS and PM-JAY portal replies are simulated. Approval is separate from payment.</p></Card>}
    {user.role === "PHARMACY" && <Card title="Medicine and device catalog" sub="Training SKUs, item tax settings and live stock" icon="▦" wide><div className="p-stock-grid">{items.map(i => <div key={i.item_code}><div><b>{i.description}</b><code>{i.item_code}</code></div><Tag tone={i.tax_category === "NIL" ? "green" : "blue"}>{i.tax_category === "NIL" ? "Nil GST" : `${i.tax_rate_bps / 100}% GST`}</Tag><span>HSN {i.hsn_code} · {i.available_units} units · {money(i.unit_price_paise)}</span></div>)}</div><p className="p-fineprint">Specific product classification must be checked before real billing. The nil-rate contraceptive is a generic training item, not a branded medicine.</p></Card>}
    <div className="p-grid p-bottom"><Card title="Running bill" sub="Charges linked to this encounter" icon="▤"><div className="p-bill-lines">{(detail.charges || []).length ? detail.charges.map((c: D) => <div key={c.charge_id}><span><b>{c.description}</b><small>{c.quantity} × {money(c.unit_price_paise)} · {c.tax_category === "TAXABLE" ? `${c.tax_rate_bps / 100}% GST` : c.tax_category}</small></span><b>{money(c.subtotal_paise + Math.round(c.subtotal_paise * c.tax_rate_bps / 10000))}</b></div>) : <p className="p-muted">No charge has been captured yet.</p>}</div><div className="p-bill-total"><span>{detail.invoice ? "Final invoice" : "Running total"}</span><b>{money(detail.invoice?.total_paise ?? detail.running_total_paise)}</b></div>{user.role === "ADMIN" && (detail.invoice ? <button className="p-primary p-open-billing" onClick={() => setInvoiceOpen(true)}>View invoice {detail.invoice.invoice_no}</button> : <button className="p-primary p-open-billing" disabled={busy || enc.status !== "OPEN" || !(detail.charges || []).length || needsCoverage || needsPreauth} onClick={generateInvoice}>Generate invoice</button>)}</Card><Card title="Next handoff" sub="One record across departments" icon="↗"><div className="p-handoff"><div><span className="done">1</span><b>Doctor note</b><small>{notes.length} recorded</small></div><div><span className={(detail.charges || []).length ? "done" : ""}>2</span><b>Service charges</b><small>{(detail.charges || []).length} line(s)</small></div><div><span className={detail.dispenses?.length ? "done" : ""}>3</span><b>Pharmacy dispense</b><small>{detail.dispenses?.length || 0} completed</small></div><div><span className={detail.invoice ? "done" : ""}>4</span><b>Final invoice</b><small>{detail.invoice?.invoice_no || "Awaiting billing"}</small></div></div></Card></div>

    {user.role === "ADMIN" && invoiceOpen && detail.invoice && <section className="p-card p-invoice-sheet" id="generated-invoice"><div className="p-invoice-toolbar"><div><span className="p-kicker">INVOICE GENERATED</span><h2>{detail.invoice.invoice_no}</h2></div><div><button className="p-secondary" onClick={() => window.print()}>Print / save PDF</button><button className="p-secondary" onClick={() => setInvoiceOpen(false)}>Close</button></div></div><div className="p-invoice-meta"><div><small>Patient</small><strong>{patient.display_label}</strong><span>{patient.patient_id}</span></div><div><small>Visit</small><strong>{selected}</strong><span>{enc.setting} · {enc.payer_route}</span></div><div><small>Date</small><strong>{when(detail.invoice.issued_at)}</strong><span>Sample invoice</span></div></div><div className="p-invoice-table"><table><thead><tr><th>Service or item</th><th>Qty</th><th>Rate</th><th>GST</th><th>Amount</th></tr></thead><tbody>{(detail.invoice_lines || []).map((line: D) => <tr key={line.invoice_line_id}><td>{line.description}</td><td>{line.quantity}</td><td>{money(line.unit_price_paise)}</td><td>{line.tax_category === "TAXABLE" ? `${line.tax_rate_bps / 100}%` : line.tax_category}</td><td>{money(line.total_paise)}</td></tr>)}</tbody></table></div><div className="p-invoice-totals"><div><span>Subtotal</span><strong>{money(detail.invoice.subtotal_paise)}</strong></div><div><span>GST</span><strong>{money(detail.invoice.tax_paise)}</strong></div><div className="grand"><span>Invoice total</span><strong>{money(detail.invoice.total_paise)}</strong></div><div><span>Balance remaining</span><strong>{money(detail.remaining_paise)}</strong></div></div>{enc.payer_route === "SELF" && detail.remaining_paise > 0 && <div className="p-invoice-payment"><label className="p-field">Payment method<select value={paymentMethod} onChange={e => setPaymentMethod(e.target.value)}><option>UPI</option><option>CASH</option><option>CARD</option></select></label><button className="p-primary" disabled={busy} onClick={() => act("Payment receipt recorded", "/receipts", { invoice_id: detail.invoice.invoice_id, payer_kind: "PATIENT", amount_paise: detail.remaining_paise, method: paymentMethod })}>Record full payment {money(detail.remaining_paise)}</button></div>}<p className="p-fineprint">Classroom sample. This is not an invoice for real patient care.</p></section>}
    {user.role === "ADMIN" && <section className="p-card p-tax-review"><div><h3>Monthly GST review</h3><p>Preview the GSTR-1 working totals from final invoices. This is a review packet, not a portal filing.</p></div><button className="p-secondary" disabled={busy} onClick={loadTaxReport}>Load this month</button>{taxReport && <div className="p-tax-results"><span>Taxable B2C groups: {taxReport.tables?.table7?.length || 0}</span><span>Nil and exempt groups: {taxReport.tables?.table8?.length || 0}</span><span>HSN rows: {taxReport.tables?.table12?.length || 0}</span></div>}</section>}
    </div></main></div>;
}
