"use client";

import { useCallback, useEffect, useState } from "react";

type Row = Record<string, any>;
type Staff = { username: string; display_name: string; role: "ADMIN" | "DOCTOR" | "LAB" | "PHARMACY" };
const demoPatient = "P-DEMO-09";
const roles = [
  { id: "admin", name: "Billing", task: "Account and invoice", icon: "₹" },
  { id: "doctor", name: "Doctor", task: "Encounter and orders", icon: "+" },
  { id: "lab", name: "Laboratory", task: "Test result", icon: "L" },
  { id: "pharmacy", name: "Pharmacy", task: "Dispense medicine", icon: "Rx" },
];
const money = (n?: number) => `₹${((n || 0) / 100).toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const dateText = (s?: string) => s ? new Date(s).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" }) : "";
const today = (days = 0) => new Date(Date.now() + days * 86400000).toISOString().slice(0, 10);

async function api(path: string, init: RequestInit = {}) {
  const token = typeof window === "undefined" ? "" : sessionStorage.getItem("tiveri_token") || "";
  const response = await fetch(`/api${path}`, { cache: "no-store", ...init,
    headers: { ...(init.body ? { "Content-Type": "application/json" } : {}), ...(token ? { Authorization: `Bearer ${token}` } : {}), ...init.headers } });
  const body = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(body.detail || `Request failed (${response.status})`);
  return body;
}
const post = (path: string, body: Row) => api(path, { method: "POST", body: JSON.stringify(body) });
function Tag({ children, tone = "blue" }: { children: React.ReactNode; tone?: string }) { return <span className={`p-tag ${tone}`}>{children}</span>; }
function Card({ title, sub, icon, children, wide = false }: { title: string; sub: string; icon: string; children: React.ReactNode; wide?: boolean }) {
  return <section className={`p-card ${wide ? "p-wide" : ""}`}><div className="p-card-head"><span className="p-card-icon">{icon}</span><div><h3>{title}</h3><small>{sub}</small></div></div>{children}</section>;
}

export default function Home() {
  const [user, setUser] = useState<Staff | null>(null);
  const [loginRole, setLoginRole] = useState("admin");
  const [password, setPassword] = useState("Demo@1234");
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [selected, setSelected] = useState(demoPatient);
  const [patients, setPatients] = useState<Row[]>([]);
  const [record, setRecord] = useState<Row>({});
  const [detail, setDetail] = useState<Row>({});
  const [stock, setStock] = useState<Row>({ items: [] });
  const [labQueue, setLabQueue] = useState<Row>({ orders: [] });
  const [note, setNote] = useState("Known type 2 diabetes without documented complications. Follow-up assessment completed. HbA1c requested and current medicine plan reviewed.");
  const [medicineQty, setMedicineQty] = useState(10);
  const [result, setResult] = useState("7.2");
  const [dispenseQty, setDispenseQty] = useState(10);
  const [roomCode, setRoomCode] = useState("PRIVATE_ROOM");
  const [roomStart, setRoomStart] = useState(today());
  const [roomEnd, setRoomEnd] = useState(today(1));
  const [invoiceOpen, setInvoiceOpen] = useState(false);
  const [paymentMethod, setPaymentMethod] = useState("UPI");
  const [taxReport, setTaxReport] = useState<Row | null>(null);

  const refresh = useCallback(async (patientId: string) => {
    const [directory, patient, inventory, lab] = await Promise.all([
      api("/patients"), api(`/patients/${patientId}`), api("/pharmacy/stock"), api("/lab/queue")]);
    setPatients(directory.patients || []); setRecord(patient); setStock(inventory); setLabQueue(lab);
    setDetail(patient.encounters?.[0] ? await api(`/encounters/${patient.encounters[0].encounter_id}`) : {});
  }, []);
  useEffect(() => {
    const saved = sessionStorage.getItem("tiveri_patient_id") || demoPatient;
    setSelected(saved);
    if (!sessionStorage.getItem("tiveri_token")) { setLoading(false); return; }
    api("/auth/me").then((staff: Staff) => { setUser(staff); return refresh(saved); })
      .catch(() => { sessionStorage.removeItem("tiveri_token"); setUser(null); }).finally(() => setLoading(false));
  }, [refresh]);
  useEffect(() => { if (invoiceOpen) requestAnimationFrame(() => document.getElementById("generated-invoice")?.scrollIntoView({ behavior: "smooth" })); }, [invoiceOpen]);

  async function login() {
    setBusy(true); setError(""); setNotice("");
    try { const response = await post("/auth/login", { username: loginRole, password }); sessionStorage.setItem("tiveri_token", response.token); setUser(response.user); await refresh(selected); }
    catch (cause) { setError((cause as Error).message); } finally { setBusy(false); }
  }
  async function logout() { await api("/auth/logout", { method: "POST" }).catch(() => {}); sessionStorage.removeItem("tiveri_token"); setUser(null); setInvoiceOpen(false); setNotice(""); setError(""); }
  async function choose(patientId: string) { setSelected(patientId); sessionStorage.setItem("tiveri_patient_id", patientId); setInvoiceOpen(false); setError(""); setNotice(""); try { await refresh(patientId); } catch (cause) { setError((cause as Error).message); } }
  async function act(label: string, path: string, payload: Row) { setBusy(true); setError(""); setNotice(""); try { await post(path, payload); await refresh(selected); setNotice(label); } catch (cause) { setError((cause as Error).message); } finally { setBusy(false); } }
  async function generateInvoice() { setBusy(true); setError(""); try { await post("/invoices", { encounter_id: encounter.encounter_id }); await refresh(selected); setInvoiceOpen(true); setNotice("Itemised invoice generated below."); } catch (cause) { setError((cause as Error).message); } finally { setBusy(false); } }
  async function resetDemo() { setBusy(true); setError(""); try { await post("/demo/reset", {}); sessionStorage.removeItem("tiveri_token"); sessionStorage.setItem("tiveri_patient_id", demoPatient); setSelected(demoPatient); setUser(null); setInvoiceOpen(false); setTaxReport(null); setNotice("Synthetic cases restored. Sign in to begin again."); } catch (cause) { setError((cause as Error).message); } finally { setBusy(false); } }

  if (loading) return <div className="p-loading">Opening the hospital demo…</div>;
  if (!user) return <main className="p-login"><section className="p-login-story"><div className="p-logo"><span>+</span><b>Tiveri</b><small>HOSPITAL OPERATIONS</small></div><div className="p-login-copy"><div className="p-kicker">DH 308 · LIVE PROJECT</div><h1>One patient.<br />Four connected desks.</h1><p>Follow an OPD visit from doctor assessment through laboratory, pharmacy and the final bill.</p><div className="p-steps"><span>01 Doctor</span><i /><span>02 Lab</span><i /><span>03 Pharmacy</span><i /><span>04 Billing</span></div></div><div className="p-login-foot">Synthetic patient and result data · External portals are simulated</div></section><section className="p-login-panel"><div className="p-login-inner"><div className="p-kicker">STAFF ACCESS</div><h2>Sign in for the demo</h2><p>Complete a handoff, sign out and open the next desk. Your selected patient stays in view.</p><div className="p-role-grid">{roles.map(role => <button key={role.id} className={`p-role ${loginRole === role.id ? "selected" : ""}`} onClick={() => setLoginRole(role.id)}><span className="p-role-icon">{role.icon}</span><span><b>{role.name}</b><small>{role.task}</small></span><span>{loginRole === role.id ? "✓" : ""}</span></button>)}</div><label className="p-field">Demo password<input type="password" value={password} onChange={event => setPassword(event.target.value)} onKeyDown={event => { if (event.key === "Enter") login(); }} /></label><div className="p-hint">Password for all roles: <code>Demo@1234</code></div>{error && <div className="p-alert error">{error}</div>}{notice && <div className="p-alert success">{notice}</div>}<button className="p-primary p-signin" disabled={busy} onClick={login}>Continue as {roles.find(role => role.id === loginRole)?.name}<span>↗</span></button></div></section></main>;

  const patient = record.patient || {};
  const encounter = detail.encounter || {};
  const eid = encounter.encounter_id || "";
  const notes: Row[] = detail.clinical_notes || [];
  const labs: Row[] = detail.lab_orders || [];
  const prescriptions: Row[] = detail.prescriptions || [];
  const pendingLab = labs.find(order => order.status === "ORDERED");
  const pendingRx = prescriptions.find(rx => rx.quantity > rx.dispensed_quantity);
  const medicine = (stock.items || []).find((item: Row) => item.item_code === pendingRx?.item_code);
  const coverage = detail.coverage || {};
  const preauth = detail.preauths?.[detail.preauths.length - 1];
  const claim = detail.claim;
  const canInvoice = encounter.status === "OPEN" && detail.charges?.length && !pendingLab && !pendingRx &&
    !(encounter.payer_route === "PMJAY" && coverage.eligibility_status !== "VERIFIED_DEMO") &&
    !(coverage.preauth_required && preauth?.status !== "APPROVED_DEMO");
  const title = { ADMIN: "Billing desk", DOCTOR: "Doctor desk", LAB: "Laboratory desk", PHARMACY: "Pharmacy desk" }[user.role];

  return <div className="p-shell"><aside className="p-sidebar"><div className="p-logo dark"><span>+</span><b>Tiveri</b></div><div className="p-side-label">SIGNED IN</div><div className="p-side-person"><span>{roles.find(role => role.id === user.username)?.icon}</span><div><b>{title}</b><small>{user.display_name}</small></div></div><div className="p-side-label">PATIENT RECORDS</div><div className="p-side-list">{patients.map(row => <button key={row.patient_id} className={selected === row.patient_id ? "active" : ""} onClick={() => choose(row.patient_id)}><span className="p-avatar">{row.display_label?.split(" ").map((part: string) => part[0]).join("")}</span><span><b>{row.display_label}</b><small>{row.patient_id}{row.patient_id === demoPatient ? " · live case" : ""}</small></span></button>)}</div><div className="p-sidebar-foot"><span className="p-dot" /> PostgreSQL connected <button onClick={logout}>Sign out ↗</button></div></aside><main className="p-main"><header className="p-topbar"><div><div className="p-kicker">DH 308 · HIS AND BILLING</div><h1>{title}</h1></div><div className="p-topright"><Tag tone="green">Live demo</Tag><span>{user.display_name}<small>{user.role.toLowerCase()}</small></span>{user.role === "ADMIN" && <button onClick={resetDemo} disabled={busy}>Reset demo</button>}<button className="p-top-signout" onClick={logout}>Sign out</button></div></header><div className="p-content">{error && <div className="p-alert error">{error}<button onClick={() => setError("")}>×</button></div>}{notice && <div className="p-alert success">{notice}<button onClick={() => setNotice("")}>×</button></div>}
    <section className="p-patient"><div className="p-patient-top"><div><div className="p-kicker">PATIENT RECORD · {patient.patient_id}</div><h2>{patient.display_label || "Choose a patient"}</h2><p>{patient.age_years} years · {patient.sex} · {patient.city} · {patient.contact_masked}</p></div><div className="p-patient-tags">{eid ? <><Tag>{encounter.setting}</Tag><Tag tone={encounter.status === "OPEN" ? "amber" : "green"}>{encounter.status}</Tag></> : <Tag tone="amber">Ready for encounter</Tag>}</div></div><div className="p-patient-facts"><div><small>Patient ID</small><b>{patient.patient_id}</b></div><div><small>Blood group</small><b>{patient.blood_group || "Not recorded"}</b></div><div><small>Allergies</small><b>{patient.allergies || "Not recorded"}</b></div><div><small>Visit</small><b>{eid || "Not started"}</b></div></div></section>
    <div className="p-workflow"><div><span className={notes.length ? "done" : ""}>1</span><b>Doctor</b><small>{notes.length ? "Encounter saved" : "Assessment pending"}</small></div><div><span className={labs.some(order => order.status === "COMPLETED") ? "done" : ""}>2</span><b>Lab</b><small>{pendingLab ? "Test ordered" : labs.length ? "Result recorded" : "Awaiting order"}</small></div><div><span className={detail.dispenses?.length ? "done" : ""}>3</span><b>Pharmacy</b><small>{pendingRx ? "Prescription waiting" : detail.dispenses?.length ? "Dispensed" : "Awaiting order"}</small></div><div><span className={detail.invoice ? "done" : ""}>4</span><b>Billing</b><small>{detail.invoice ? "Invoice generated" : "Running bill"}</small></div></div>
    <div className="p-intro"><div><div className="p-kicker">SHARED PATIENT RECORD</div><h2>{user.role === "DOCTOR" ? "Assessment and orders" : user.role === "LAB" ? "Laboratory worklist" : user.role === "PHARMACY" ? "Prescription and stock" : "Charges and invoice"}</h2></div><p>{user.role === "DOCTOR" ? "Confirm the prepared case. Codes appear before you create the visit." : user.role === "LAB" ? "The doctor order appears here. Completing it posts a lab charge once." : user.role === "PHARMACY" ? "Dispense against the prescription and available stock." : "Each completed service appears automatically on this account."}</p></div>
    <div className="p-grid"><Card title="Clinical history" sub="Synthetic patient information" icon="H"><p className="p-history">{patient.history_summary || "No history entered for this synthetic patient."}</p>{notes.length > 0 && <><div className="p-mini-heading">Doctor assessment</div>{notes.slice(0, 2).map(n => <div className="p-note" key={n.note_id}><b>{dateText(n.created_at)} · {n.author_username}</b><p>{n.note_text}</p><small>ICD-10 {n.provisional_icd_code || "—"} · CPT {n.procedure_code || "—"} reference</small></div>)}</>}{labs.length > 0 && <><div className="p-mini-heading">Laboratory</div>{labs.map(order => <div className="p-note" key={order.lab_order_id}><b>{order.description} · LOINC {order.loinc_code}</b><p>{order.status === "COMPLETED" ? `Result: ${order.result_value}${order.result_unit} · ${dateText(order.completed_at)}` : "Ordered by doctor. Result pending."}</p></div>)}</>}</Card>
    {user.role === "DOCTOR" && !eid && selected === demoPatient && <Card title="Create the OPD encounter" sub="Type 2 diabetes follow-up" icon="+"><label className="p-field">Encounter note<textarea rows={4} value={note} onChange={event => setNote(event.target.value)} /></label><div className="p-code-grid"><div><small>Diagnosis</small><b>ICD-10 E11.9</b><span>Type 2 diabetes without complications</span></div><div><small>Lab observation</small><b>LOINC 4548-4</b><span>HbA1c in blood</span></div><div><small>Procedure reference</small><b>CPT 83036</b><span>Optional, not the local tariff</span></div><div><small>Local billing</small><b>CONSULT + HBA1C</b><span>₹500 now; ₹650 after lab</span></div></div><label className="p-field">Metformin 500 mg training tablets<input type="number" min="1" max="100" value={medicineQty} onChange={event => setMedicineQty(Number(event.target.value))} /></label><p className="p-fineprint">You confirm this fixed teaching pathway. The software does not diagnose from free text. Medicine details are synthetic.</p><button className="p-primary" disabled={busy || note.trim().length < 15 || medicineQty < 1} onClick={() => act("Encounter saved. Lab and pharmacy orders are ready.", "/clinical/demo-encounters", { patient_id: selected, case_code: "DIABETES_FOLLOWUP", note_text: note, medicine_item_code: "MED-M", medicine_quantity: medicineQty, instruction: "Existing plan reviewed by the doctor. Synthetic demonstration only." })}>Create encounter and send orders</button></Card>}
    {user.role === "DOCTOR" && eid && <Card title="Encounter recorded" sub="Orders sent to lab and pharmacy" icon="✓"><div className="p-review"><small>VISIT</small><b>{eid}</b><span>ICD-10 {notes[0]?.provisional_icd_code || "—"} · CPT {notes[0]?.procedure_code || "—"} reference</span></div><div className="p-summary-list"><div><span>Consultation</span><b>{detail.charges?.some((charge: Row) => charge.service_code === "CONSULT") ? "Charged" : "Pending"}</b></div><div><span>HbA1c</span><b>{labs[0]?.status || "Not ordered"}</b></div><div><span>Medicine</span><b>{prescriptions[0] ? `${prescriptions[0].quantity} tablets ordered` : "Not ordered"}</b></div></div></Card>}
    {user.role === "LAB" && <Card title="Ordered test" sub="Result and HIS charge" icon="L">{pendingLab ? <><div className="p-review"><small>ORDER #{pendingLab.lab_order_id}</small><b>{pendingLab.description}</b><span>LOINC {pendingLab.loinc_code} · Blood · local service {pendingLab.service_code}</span></div><label className="p-field">Synthetic HbA1c result (%)<input type="number" min="0.1" max="29.9" step="0.1" value={result} onChange={event => setResult(event.target.value)} /></label><button className="p-primary" disabled={busy || !Number(result)} onClick={() => act("Lab result recorded. HbA1c charge posted.", `/lab/orders/${pendingLab.lab_order_id}/complete`, { result_value: Number(result) })}>Complete test and post charge</button><p className="p-fineprint">LOINC identifies the observation. HBA1C is the hospital billing code. CPT 83036 is an optional reference.</p></> : labs.length ? <div className="p-review"><small>TEST COMPLETE</small><b>{labs[0].description}</b><span>LOINC {labs[0].loinc_code} · {labs[0].result_value}{labs[0].result_unit} · charge posted once</span></div> : <p className="p-history">No test has been ordered for this patient. Select Asha Kulkarni after the doctor creates her visit.</p>}{labQueue.orders?.filter((order: Row) => order.status === "ORDERED").length > 0 && <p className="p-fineprint">Pending lab orders across the demo: {labQueue.orders.filter((order: Row) => order.status === "ORDERED").length}.</p>}</Card>}
    {user.role === "PHARMACY" && <Card title="Prescription" sub="Dispense from the stocked batch" icon="Rx">{pendingRx ? <><div className="p-review"><small>{pendingRx.prescription_ref}</small><b>{medicine?.description || pendingRx.item_code}</b><span>{pendingRx.quantity - pendingRx.dispensed_quantity} to dispense · {medicine?.tax_rate_bps / 100}% GST · HSN {medicine?.hsn_code}</span></div><p className="p-fineprint">{pendingRx.instruction}</p><label className="p-field">Quantity to dispense<input type="number" min="1" max={pendingRx.quantity - pendingRx.dispensed_quantity} value={dispenseQty} onChange={event => setDispenseQty(Number(event.target.value))} /></label><button className="p-primary" disabled={busy || dispenseQty < 1 || dispenseQty > pendingRx.quantity - pendingRx.dispensed_quantity} onClick={() => act("Medicine dispensed. Stock and bill updated.", "/pharmacy/dispense", { encounter_id: eid, item_code: pendingRx.item_code, quantity: dispenseQty, prescription_ref: pendingRx.prescription_ref, source_event_id: `DISP-${crypto.randomUUID()}` })}>Dispense medicine</button></> : detail.dispenses?.length ? <div className="p-review"><small>DISPENSED</small><b>{detail.dispenses.length} stock transaction(s)</b><span>Charge now visible at the billing desk.</span></div> : <p className="p-history">No prescription for this patient yet. The doctor creates it with the encounter.</p>}</Card>}
    {user.role === "ADMIN" && <Card title="Billing review" sub="One running account" icon="₹">{eid ? <><div className="p-summary-list"><div><span>Diagnosis</span><b>{notes[0]?.provisional_icd_code || "Pending"}</b></div><div><span>Lab test</span><b>{pendingLab ? "Awaiting lab" : labs.length ? "Completed" : "None"}</b></div><div><span>Medicine</span><b>{pendingRx ? "Awaiting pharmacy" : detail.dispenses?.length ? "Dispensed" : "None"}</b></div></div><p className="p-fineprint">Only delivered consultation, completed lab work and dispensed medicines create charges. A diagnosis has no price.</p></> : <p className="p-history">This patient is already registered. Sign in as doctor and create the follow-up encounter to begin the handoff.</p>}</Card>}
    </div>
    {user.role === "ADMIN" && encounter.setting === "IPD" && encounter.status === "OPEN" && <Card title="Room stay" sub="Inpatient example" icon="B" wide><div className="p-room-options"><button className={roomCode === "WARD" ? "selected" : ""} onClick={() => setRoomCode("WARD")}><span>General ward</span><b>₹2,300 / day</b><small>Exempt example</small></button><button className={roomCode === "PRIVATE_ROOM" ? "selected" : ""} onClick={() => setRoomCode("PRIVATE_ROOM")}><span>Private non-ICU room</span><b>₹6,000 / day</b><small>5% GST, subject to conditions</small></button></div><div className="p-two-fields"><label className="p-field">From<input type="date" value={roomStart} onChange={event => setRoomStart(event.target.value)} /></label><label className="p-field">To, exclusive<input type="date" value={roomEnd} onChange={event => setRoomEnd(event.target.value)} /></label></div><button className="p-secondary" disabled={busy} onClick={() => act("Room stay added.", `/encounters/${eid}/room-stays`, { room_code: roomCode, start_date: roomStart, end_date: roomEnd })}>Add room stay</button></Card>}
    {user.role === "ADMIN" && eid && encounter.payer_route !== "SELF" && <Card title="Payer pathway" sub={`${encounter.payer_label} · simulated external response`} icon="P" wide><div className="p-summary-list"><div><span>Coverage</span><b>{coverage.eligibility_status}</b></div><div><span>Preauthorisation</span><b>{preauth?.status || "Not requested"}</b></div><div><span>Claim</span><b>{claim?.status || "Not submitted"}</b></div></div><div className="p-action-row">{encounter.payer_route === "PMJAY" && coverage.eligibility_status !== "VERIFIED_DEMO" && <button className="p-secondary" disabled={busy} onClick={() => act("Beneficiary check recorded.", `/coverage/${eid}/verify`, { member_ref: `SYN-${eid}` })}>Verify beneficiary</button>}{coverage.preauth_required && !preauth && <button className="p-secondary" disabled={busy} onClick={() => act("Preauthorisation requested.", "/preauth", { encounter_id: eid, requested_paise: Math.max(detail.running_total_paise || 0, 1500000) })}>Request preauthorisation</button>}{preauth?.status === "SUBMITTED_DEMO" && <button className="p-secondary" disabled={busy} onClick={() => act("Preauthorisation approved.", `/preauth/${preauth.preauth_id}/decision`, { approved_paise: preauth.requested_paise, reference_no: `SYN-PRE-${eid}` })}>Record approval</button>}{detail.invoice && !claim && <button className="p-secondary" disabled={busy} onClick={() => act("Claim prepared.", "/claims", { invoice_id: detail.invoice.invoice_id, discharge_summary: "Synthetic discharge summary.", documents: { itemised_bill: true, discharge_summary: true } })}>Prepare claim</button>}{claim?.status === "SUBMITTED_DEMO" && <button className="p-secondary" disabled={busy} onClick={() => act("Claim decision recorded.", `/claims/${claim.claim_id}/decision`, { approved_paise: claim.submitted_paise, reference_no: `SYN-CLM-${eid}` })}>Record claim decision</button>}</div></Card>}
    {user.role === "PHARMACY" && <Card title="Medicine catalog" sub="Training items and tax settings" icon="M" wide><div className="p-stock-grid">{(stock.items || []).map((item: Row) => <div key={item.item_code}><div><b>{item.description}</b><code>{item.item_code}</code></div><Tag tone={item.tax_category === "NIL" ? "green" : "blue"}>{item.tax_category === "NIL" ? "Nil GST" : `${item.tax_rate_bps / 100}% GST`}</Tag><span>HSN {item.hsn_code} · {item.available_units} in stock · {money(item.unit_price_paise)}</span></div>)}</div><p className="p-fineprint">Check the actual product classification before any real billing.</p></Card>}
    <div className="p-grid p-bottom"><Card title="Running bill" sub="Charges from completed work" icon="₹"><div className="p-bill-lines">{detail.charges?.length ? detail.charges.map((charge: Row) => <div key={charge.charge_id}><span><b>{charge.description}</b><small>{charge.service_code} · {charge.quantity} × {money(charge.unit_price_paise)} · {charge.tax_category === "TAXABLE" ? `${charge.tax_rate_bps / 100}% GST` : charge.tax_category}</small></span><b>{money(charge.subtotal_paise + Math.round(charge.subtotal_paise * charge.tax_rate_bps / 10000))}</b></div>) : <p className="p-muted">No delivered service has been charged yet.</p>}</div><div className="p-bill-total"><span>{detail.invoice ? "Final invoice" : "Running total"}</span><b>{money(detail.invoice?.total_paise ?? detail.running_total_paise)}</b></div>{user.role === "ADMIN" && (detail.invoice ? <button className="p-primary p-open-billing" onClick={() => setInvoiceOpen(true)}>View invoice {detail.invoice.invoice_no}</button> : <><button className="p-primary p-open-billing" disabled={busy || !canInvoice} onClick={generateInvoice}>Generate itemised invoice</button>{pendingLab || pendingRx ? <p className="p-fineprint">Complete pending lab and pharmacy work before invoicing.</p> : null}</>)}</Card><Card title="Handoff record" sub="Same encounter across departments" icon="↗"><div className="p-handoff"><div><span className={notes.length ? "done" : ""}>1</span><b>Doctor</b><small>{notes.length ? "Recorded" : "Pending"}</small></div><div><span className={labs.some(order => order.status === "COMPLETED") ? "done" : ""}>2</span><b>Lab</b><small>{pendingLab ? "Ordered" : labs.length ? "Completed" : "Pending"}</small></div><div><span className={detail.dispenses?.length ? "done" : ""}>3</span><b>Pharmacy</b><small>{pendingRx ? "Ordered" : detail.dispenses?.length ? "Dispensed" : "Pending"}</small></div><div><span className={detail.invoice ? "done" : ""}>4</span><b>Invoice</b><small>{detail.invoice?.invoice_no || "Pending"}</small></div></div></Card></div>
    {user.role === "ADMIN" && invoiceOpen && detail.invoice && <section className="p-card p-invoice-sheet" id="generated-invoice"><div className="p-invoice-toolbar"><div><span className="p-kicker">INVOICE GENERATED</span><h2>{detail.invoice.invoice_no}</h2></div><div><button className="p-secondary" onClick={() => window.print()}>Print or save PDF</button><button className="p-secondary" onClick={() => setInvoiceOpen(false)}>Close</button></div></div><div className="p-invoice-meta"><div><small>Patient</small><strong>{patient.display_label}</strong><span>{patient.patient_id}</span></div><div><small>Visit</small><strong>{eid}</strong><span>{encounter.setting} · {encounter.payer_route}</span></div><div><small>Date</small><strong>{dateText(detail.invoice.issued_at)}</strong><span>Classroom sample</span></div></div><div className="p-invoice-table"><table><thead><tr><th>Service or item</th><th>Qty</th><th>Rate</th><th>GST</th><th>Amount</th></tr></thead><tbody>{(detail.invoice_lines || []).map((line: Row) => <tr key={line.invoice_line_id}><td>{line.description}</td><td>{line.quantity}</td><td>{money(line.unit_price_paise)}</td><td>{line.tax_category === "TAXABLE" ? `${line.tax_rate_bps / 100}%` : line.tax_category}</td><td>{money(line.total_paise)}</td></tr>)}</tbody></table></div><div className="p-invoice-totals"><div><span>Subtotal</span><strong>{money(detail.invoice.subtotal_paise)}</strong></div><div><span>GST</span><strong>{money(detail.invoice.tax_paise)}</strong></div><div className="grand"><span>Invoice total</span><strong>{money(detail.invoice.total_paise)}</strong></div><div><span>Balance remaining</span><strong>{money(detail.remaining_paise)}</strong></div></div>{encounter.payer_route === "SELF" && detail.remaining_paise > 0 && <div className="p-invoice-payment"><label className="p-field">Payment method<select value={paymentMethod} onChange={event => setPaymentMethod(event.target.value)}><option>UPI</option><option>CASH</option><option>CARD</option></select></label><button className="p-primary" disabled={busy} onClick={() => act("Payment receipt recorded.", "/receipts", { invoice_id: detail.invoice.invoice_id, payer_kind: "PATIENT", amount_paise: detail.remaining_paise, method: paymentMethod })}>Record payment {money(detail.remaining_paise)}</button></div>}<p className="p-fineprint">Synthetic classroom invoice. Not for real patient care.</p></section>}
    {user.role === "ADMIN" && <section className="p-card p-tax-review"><div><h3>GST review</h3><p>Preview taxable and exempt totals from final invoices.</p></div><button className="p-secondary" disabled={busy} onClick={async () => { setBusy(true); setError(""); try { setTaxReport(await api(`/gstr1?month=${today().slice(0, 7)}`)); } catch (cause) { setError((cause as Error).message); } finally { setBusy(false); } }}>Load this month</button>{taxReport && <div className="p-tax-results"><span>Taxable B2C groups: {taxReport.tables?.table7?.length || 0}</span><span>Nil and exempt groups: {taxReport.tables?.table8?.length || 0}</span><span>HSN rows: {taxReport.tables?.table12?.length || 0}</span></div>}</section>}
  </div></main></div>;
}
